AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  go-csv-txt-xsl

Resources:
  AppSyncServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - appsync.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: AllowAccessForAppsyncResolvers
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - states:StartSyncExecution #Type: Express
                Resource:
                  - !Ref UploadFileStateMachine
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:DeleteItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: 
                  - !GetAtt DB.Arn
                  - !Sub 
                    - "${Table}/index/*"
                    - { Table: !GetAtt DB.Arn }

  AppSyncApi:
    DependsOn: AppSyncServiceRole
    Type: AWS::AppSync::GraphQLApi
    Description: "The GraphQL API for the single table App"
    Properties:
      Name: AppSyncTestAPI
      AuthenticationType: API_KEY

  # API Key for external access
  AppSyncApiKey:
    Type: AWS::AppSync::ApiKey
    Properties: 
      ApiId: !GetAtt AppSyncApi.ApiId

  # AppSync Schema
  AppSyncSchema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      DefinitionS3Location: "./schema.graphql"

  # AppSync Data Source for DynamoDB
  AppSyncTableDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      Name: Tramas
      ApiId: !GetAtt AppSyncApi.ApiId
      Description: "The Single Table AppSync Data Source"
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
      DynamoDBConfig:
        TableName: !Ref DB
        AwsRegion: !Sub ${AWS::Region}

   # AppSync Data Source for StepFunction
  StepFunctionsHttpDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      Name: StepFunctionsHttpDataSource
      Description: Step Functions HTTP
      Type: HTTP
      ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
      HttpConfig:
        Endpoint: !Sub https://sync-states.${AWS::Region}.amazonaws.com/
        AuthorizationConfig:
          AuthorizationType: AWS_IAM
          AwsIamConfig:
            SigningRegion: !Ref AWS::Region
            SigningServiceName: states


 ###############      
 ## RESOLVERS ##
 ###############  

  UploadFileResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: AppSyncSchema
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Mutation
      FieldName: uploadFile
      DataSourceName: !GetAtt StepFunctionsHttpDataSource.Name
      RequestMappingTemplate: !Sub >
        {
          "version": "2018-05-29",
          "method": "POST",
          "resourcePath": "/",
          "params": {
            "headers": {
              "content-type": "application/x-amz-json-1.0",
              "x-amz-target":"AWSStepFunctions.StartSyncExecution"
            },
            "body": {
              "stateMachineArn": "${UploadFileStateMachine}",
              "input": "{ \"input\": $util.escapeJavaScript($util.toJson($ctx.args.input))}"
            }
          }
        }
      ResponseMappingTemplate: $ctx.result.body

 ###################      
 ## STATEMACHINES ##
 ###################
  UploadFileStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachines/upload_file.asl.json
      Type: EXPRESS
      Name: desg-upload-file
      DefinitionSubstitutions:  
        TableName: !Ref DB
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt UploadFileLogs.Arn
        IncludeExecutionData: true
        Level: ALL  
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: !Ref DB 
        - CloudWatchLogsFullAccess


 ###############      
 ## LOGS      ##
 ###############  

  TransformCSV:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/vendedlogs/states/${AWS::StackName}/transform-csv
      RetentionInDays: 3

  TransformXSL:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/vendedlogs/states/${AWS::StackName}/transform-xsl
      RetentionInDays: 3
  
  UploadFileLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/vendedlogs/states/${AWS::StackName}/upload-file
      RetentionInDays: 3



  # DynamoDB
  DB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Tramas
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: number
          AttributeType: S        
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: number
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

# Functions
  TransformCSVFunction:         
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/transform-csv
      Handler: test-transform-csv
      Runtime: go1.x
      MemorySize: 2048 
      Timeout: 300
      Environment:
        Variables:
          BUCKET_NAME: !Ref DataBucket
          TABLA_NAME: !Ref DB
          REGION: !Sub ${AWS::Region}
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: !Ref DB
        - AWSLambdaBasicExecutionRole
        - S3ReadPolicy:
            BucketName: !Ref DataBucket
      Events:
        EBRule:
          Type: EventBridgeRule
          Properties:
            InputPath: "$.detail"
            Pattern:
              detail:
                bucket:
                  name:
                    - !Ref DataBucket                
              detail-type:
                - "Object Created"
              source:
                - aws.s3 

  TransformXSLFunction:         
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/transform-xsl
      Handler: test-transform-xsl
      Runtime: go1.x
      MemorySize: 2048 
      Timeout: 300
      Environment:
        Variables:
          BUCKET_NAME: !Ref DataBucket
          TABLA_NAME: !Ref DB
          REGION: !Sub ${AWS::Region}
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: !Ref DB
        - AWSLambdaBasicExecutionRole
        - S3ReadPolicy:
            BucketName: !Ref DataBucket
      Events:
        EBRule:
          Type: EventBridgeRule
          Properties:
            InputPath: "$.detail"
            Pattern:
              detail:
                bucket:
                  name:
                    - !Ref DataBucket                
              detail-type:
                - "Object Created"
              source:
                - aws.s3 

 #############################
 ## BUCKET                ####
 #############################
  DataBucket:
    Type: AWS::S3::Bucket 
    Properties:  
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: True 


Outputs:
  APIKey:
    Description: API Key
    Value: !GetAtt AppSyncApiKey.ApiKey
  GraphQLApiEndpoint:
    Description: The URL to the GraphQL Endpoint
    Value: !GetAtt AppSyncApi.GraphQLUrl
  GraphQLApiId:
    Description: The API ID of the GraphQL API
    Value: !GetAtt AppSyncApi.ApiId         
